# =============================================================================
# Prometheus Configuration for Multiplayer Game Server
# =============================================================================

global:
  scrape_interval:     2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'game_server'
    static_configs:
      - targets: ['game_server:9100', '127.0.0.1:9100']
        labels:
          service: 'multiplayer-game-server'
